"""Generate the C register map for the example MCU/fabric AHB bank."""

from __future__ import annotations

import argparse
from pathlib import Path


def render_header(base: int = 0x60000000) -> str:
    if not 0 <= base <= 0xFFFFFFFF or base & 3:
        raise ValueError("base must be an aligned 32-bit address")
    return f"""/* Generated by python -m agamemnon.mcu_register_bank. */
#ifndef AGAMEMNON_FABRIC_REGISTERS_H
#define AGAMEMNON_FABRIC_REGISTERS_H

#include <stdint.h>

#define AGAMEMNON_FABRIC_BASE       UINT32_C(0x{base:08x})
#define AGAMEMNON_FABRIC_ID_OFFSET  UINT32_C(0x00)
#define AGAMEMNON_FABRIC_SCRATCH_OFFSET UINT32_C(0x04)
#define AGAMEMNON_FABRIC_COUNTER_OFFSET UINT32_C(0x08)
#define AGAMEMNON_FABRIC_STATUS_OFFSET  UINT32_C(0x0c)

#define AGAMEMNON_FABRIC_RO32(offset) \\
  (*(volatile const uint32_t *)(uintptr_t)(AGAMEMNON_FABRIC_BASE + (offset)))
#define AGAMEMNON_FABRIC_RW32(offset) \\
  (*(volatile uint32_t *)(uintptr_t)(AGAMEMNON_FABRIC_BASE + (offset)))

#define AGAMEMNON_FABRIC_ID \\
  AGAMEMNON_FABRIC_RO32(AGAMEMNON_FABRIC_ID_OFFSET)
#define AGAMEMNON_FABRIC_SCRATCH \\
  AGAMEMNON_FABRIC_RW32(AGAMEMNON_FABRIC_SCRATCH_OFFSET)
#define AGAMEMNON_FABRIC_COUNTER \\
  AGAMEMNON_FABRIC_RO32(AGAMEMNON_FABRIC_COUNTER_OFFSET)
#define AGAMEMNON_FABRIC_STATUS \\
  AGAMEMNON_FABRIC_RW32(AGAMEMNON_FABRIC_STATUS_OFFSET)

/* Writing one clears the corresponding latched status bit. */
static inline void agamemnon_fabric_status_clear(uint32_t mask) {{
  AGAMEMNON_FABRIC_STATUS = mask;
}}

#endif
"""


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", type=lambda value: int(value, 0), default=0x60000000)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write(render_header(args.base))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
