[project]
name = "@PROJECT_NAME@"
board = "ag32vf303-l48"
device = "AGRV2KL48"

[fabric]
sources = ["logic/uart_tx.v", "logic/top.v"]
top = "top"
pcf = "board.pcf"
output = "build/fabric.bin"
uarch = true
sysclk = 25
hse = 8

[mcu]
sources = ["src/load_fabric.c"]
linker = "@sdk/link_sram.ld"
output = "build/mcu.bin"
