#!/usr/bin/env python3
"""Generate the exact primitive source mirror for route-replay regression.

This fixture is mechanically derived from the qualified routed checkpoint.  It
proves that source synthesis plus fail-closed exact route replay can reproduce
the image; it is not a portable or human-authored register-bank template.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


HERE = Path(__file__).resolve().parent
CHECKPOINT = HERE / "mcu_ahb_register_bank16_read_word0_gated_routed.json"
OUTPUT = HERE / "mcu_ahb_register_bank16_read_word0_structural.v"


def number(value):
    return int(value, 2)


def signal(bit):
    if bit in ("0", "1"):
        return "1'b" + bit
    if not isinstance(bit, int):
        raise ValueError("unsupported connection bit %r" % (bit,))
    return "n%d" % bit


def vector(bits):
    if not bits:
        return ""
    if len(bits) == 1:
        return signal(bits[0])
    # JSON connection arrays are low-to-high; concatenations are high-to-low.
    return "{" + ", ".join(signal(bit) for bit in reversed(bits)) + "}"


def generate(checkpoint=CHECKPOINT):
    design = json.loads(Path(checkpoint).read_text(encoding="utf-8"))
    top = design["modules"]["top"]
    cells = top["cells"]
    bits = sorted({
        bit
        for cell in cells.values()
        for values in cell.get("connections", {}).values()
        for bit in values
        if isinstance(bit, int)
    })
    lines = [
        "// Mechanical source mirror of the exact qualified bank16 checkpoint.",
        "// Generated by qualification/generate_mcu_ahb_bank16_read_word0_structural.py.",
        "// This is a route-replay fixture, not portable canonical RTL.",
        "(* top *) module top;",
    ]
    for bit in bits:
        lines.append("  wire n%d;" % bit)
    ground_bits = top["netnames"]["$PACKER_GND_NET"]["bits"]
    if len(ground_bits) != 1:
        raise ValueError("checkpoint ground net is not scalar")
    ground_inputs = cells["$PACKER_GND"]["connections"]["I"]
    lines.extend([
        "  (* keep *)",
        "  GENERIC_SLICE #(.K(4), .INIT(16'h0000), .FF_USED(32'd0))",
        "    route_replay_ground(.CLK(), .I(%s), .F(%s), .Q());" %
        (vector(ground_inputs), signal(ground_bits[0])),
        "",
    ])

    emitted = 0
    for name, cell in cells.items():
        # The explicit kept zero-LUT above recreates this generated cell under a
        # stable source name; exact replay maps it by its unique fingerprint and
        # verified connectivity rather than relying on the checkpoint's `$` name.
        if name == "$PACKER_GND":
            continue
        cell_type = cell["type"]
        bel = cell.get("attributes", {}).get("NEXTPNR_BEL")
        attributes = ["keep"]
        if bel:
            attributes.append('BEL = "%s"' % bel)
        lines.append("  (* " + ", ".join(attributes) + " *)")

        parameters = cell.get("parameters", {})
        if cell_type == "GENERIC_SLICE":
            ff_width = len(parameters["FF_USED"])
            lines.append(
                "  GENERIC_SLICE #(.K(%d), .INIT(16'h%04X), .FF_USED(%d'd%d)) %s("
                % (number(parameters["K"]), number(parameters["INIT"]),
                   ff_width, number(parameters["FF_USED"]), name)
            )
            connections = cell["connections"]
            ports = [
                ".CLK(%s)" % vector(connections.get("CLK", [])),
                ".I(%s)" % vector(connections.get("I", [])),
                ".F(%s)" % vector(connections.get("F", [])),
                ".Q(%s)" % vector(connections.get("Q", [])),
            ]
        else:
            lines.append("  %s %s(" % (cell_type, name))
            ports = [".%s(%s)" % (port, vector(values))
                     for port, values in cell.get("connections", {}).items()]
        lines.append("    " + ", ".join(ports) + ");")
        emitted += 1
    lines.extend(["endmodule", ""])
    return "\n".join(lines), emitted


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=Path, default=CHECKPOINT)
    parser.add_argument("--out", type=Path, default=OUTPUT)
    args = parser.parse_args()
    text, emitted = generate(args.checkpoint)
    args.out.write_bytes(text.encode("ascii"))
    print("wrote %s with %d explicit cells plus the Yosys ground packer" %
          (args.out, emitted))


if __name__ == "__main__":
    main()
