#!/usr/bin/env python3
"""Deterministic arbitrary-RTL build campaign for the open AGRV2K flow.

Each trial creates ordinary synthesizable Verilog with a wide, stateful dataflow
graph, then drives the public CLI through Yosys, the strict agrv2k uarch,
router2, timing analysis, open bitgen, and routed-netlist simulation.  A trial
passes only when routing closes, every routed data PIP has an exact encoding,
and the simulated AHB observation has more than two distinct states.

This is intentionally hardware-free.  Passing images are suitable inputs to
the workbench's SRAM-only AHB reader for silicon qualification.

Example:
  python qualification/random_rtl_campaign.py --seeds 0:8 --widths 8,16,32
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import random
import re
import subprocess
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[1]


def _mask(rng: random.Random, width: int) -> int:
    value = rng.getrandbits(width)
    value |= 1
    value |= 1 << (width - 1)
    return value


def _parity(value: int) -> int:
    return bin(value).count("1") & 1  # int.bit_count() is 3.10+; keep >=3.8 compatible


def _observation_masks(rng: random.Random, states: list[int], width: int) -> tuple[int, int]:
    """Choose two wide parity functions that expose all four combinations."""
    candidates = [_mask(rng, width) for _ in range(96)]
    best = (0, None, None)
    for pos, first in enumerate(candidates):
        if len({_parity(state & first) for state in states}) < 2:
            continue
        for second in candidates[pos + 1:]:
            combinations = {(_parity(state & first), _parity(state & second)) for state in states}
            if len(combinations) > best[0]:
                best = (len(combinations), first, second)
            if len(combinations) == 4:
                return first, second
    raise ValueError("generated state evolution cannot expose four observation states (best=%d)" % best[0])


def generate(seed: int, width: int, mode: str) -> str:
    """Return reproducible, ordinary RTL with two sensitized AHB readout bits."""
    if width < 4:
        raise ValueError("width must be at least 4")
    if mode not in ("lfsr", "xorshift", "mixed"):
        raise ValueError("unknown mode %r" % mode)
    rng = random.Random(0xA6320000 ^ seed ^ (width << 12))
    initial = _mask(rng, width)
    word_mask = (1 << width) - 1
    extra_wires = ""

    if mode == "lfsr":
        taps = sorted({width - 1, width - 2, max(1, width // 2), seed % (width - 1)})
        feedback = " ^ ".join("state[%d]" % tap for tap in taps)
        next_expr = "{state[%d:0], feedback}" % (width - 2)
        def step(value):
            bit = 0
            for tap in taps:
                bit ^= (value >> tap) & 1
            return ((value << 1) | bit) & word_mask
    elif mode == "xorshift":
        # Staged xorshift transforms are invertible for nonzero state.  The old
        # single-expression random shifts could cancel and collapse to a
        # two-state orbit, weakening the hardware oracle.
        if width <= 4:
            a, b, c = 1, 3, 2
        elif width <= 8:
            a, b, c = 7, 5, 3
        elif width <= 16:
            a, b, c = 7, 9, 8
        elif width <= 32:
            a, b, c = 13, 17, 5
        else:
            a, b, c = 13, 7, 17
        feedback = "state[%d] ^ state[%d]" % (width - 1, width // 2)
        extra_wires = ("  wire [{msb}:0] xorshift1 = state ^ (state << {a});\n"
                       "  wire [{msb}:0] xorshift2 = xorshift1 ^ (xorshift1 >> {b});\n").format(
                           msb=width - 1, a=a, b=b)
        next_expr = "xorshift2 ^ (xorshift2 << %d)" % c
        def step(value):
            value = (value ^ (value << a)) & word_mask
            value = (value ^ (value >> b)) & word_mask
            return (value ^ (value << c)) & word_mask
    else:
        a = 1 + rng.randrange(width - 1)
        b = 1 + rng.randrange(width - 1)
        feedback = "state[%d] ^ state[%d] ^ state[%d]" % (width - 1, a, b)
        # Nonlinear terms force genuine LUT logic between registers while the
        # shifted state keeps activity moving through every bit position.
        next_expr = ("{state[%d:0], feedback} ^ "
                     "((state << %d) & (state >> %d))") % (width - 2, a, b)
        def step(value):
            bit = ((value >> (width - 1)) ^ (value >> a) ^ (value >> b)) & 1
            shifted = ((value << 1) | bit) & word_mask
            return (shifted ^ ((value << a) & (value >> b))) & word_mask

    states = []
    state = initial
    for _ in range(256):
        states.append(state)
        state = step(state)
    observe0, observe1 = _observation_masks(rng, states, width)

    return """// generated by qualification/random_rtl_campaign.py; seed={seed} mode={mode}
module top(input clk);
  wire h0, h1;
  (* keep *) MCU_DOUT mcu_h0(.DOUT(h0));
  (* keep *) MCU_DOUT mcu_h1(.DOUT(h1));
  reg [{msb}:0] state = {width}'h{initial:x};
  wire feedback = {feedback};
{extra_wires}
  wire [{msb}:0] next_state = {next_expr};
  always @(posedge clk) state <= next_state;
  assign h0 = ^(state & {width}'h{observe0:x});
  assign h1 = ^(state & {width}'h{observe1:x});
endmodule
""".format(seed=seed, mode=mode, msb=width - 1, width=width,
           initial=initial, feedback=feedback, extra_wires=extra_wires, next_expr=next_expr,
           observe0=observe0, observe1=observe1)


def generate_ahb_step(seed: int, width: int, mode: str) -> str:
    """Generate the same state machine with one update per External-AHB write.

    This variant is for silicon qualification, not the hardware-free campaign:
    a write followed by a read gives a deterministic state sample and cannot
    alias a long-period machine against the MCU/fabric clock ratio.  The uarch
    binds these conventional MCU_DIN instance names to hwdata0/hwrite/htrans1.
    """
    source = generate(seed, width, mode)
    source = source.replace(
        "// generated by qualification/random_rtl_campaign.py;",
        "// AHB-step hardware oracle generated by qualification/random_rtl_campaign.py;",
        1,
    )
    source = source.replace(
        "  wire h0, h1;\n",
        "  wire h0, h1, hwdata0, hwrite, htrans1;\n",
        1,
    )
    source = source.replace(
        "  (* keep *) MCU_DOUT mcu_h1(.DOUT(h1));\n",
        "  (* keep *) MCU_DOUT mcu_h1(.DOUT(h1));\n"
        "  (* keep *) MCU_DIN mcu_hwdata0(.DIN(hwdata0));\n"
        "  (* keep *) MCU_DIN mcu_hwrite(.DIN(hwrite));\n"
        "  (* keep *) MCU_DIN mcu_htrans1(.DIN(htrans1));\n",
        1,
    )
    source = source.replace(
        "  wire feedback = ",
        "  reg wr_ph = 1'b0;\n  wire feedback = ",
        1,
    )
    source = source.replace(
        "  always @(posedge clk) state <= next_state;",
        "  always @(posedge clk) begin\n"
        "    wr_ph <= hwrite & htrans1;\n"
        "    if (wr_ph) state <= next_state;\n"
        "  end",
        1,
    )
    return source


def _sha256_binary(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _sha256_text(path: Path) -> str:
    data = path.read_bytes().replace(b"\r\n", b"\n").replace(b"\r", b"\n")
    return hashlib.sha256(data).hexdigest()


def _parse_range(text: str) -> list[int]:
    result: list[int] = []
    for part in text.split(","):
        part = part.strip()
        if not part:
            continue
        if ":" in part:
            lo, hi = (int(value, 0) for value in part.split(":", 1))
            result.extend(range(lo, hi))
        else:
            result.append(int(part, 0))
    if not result:
        raise ValueError("empty seed set")
    return result


def run_trial(seed: int, width: int, mode: str, frequency: float,
              directory: Path, timeout: int) -> dict:
    tag = "%s_w%d_s%d" % (mode, width, seed)
    source = directory / (tag + ".v")
    bitstream = directory / (tag + ".bin")
    routed = directory / (tag + "_routed.json")
    source.write_text(generate(seed, width, mode), encoding="utf-8")
    command = [
        sys.executable, "-m", "agamemnon.cli", "build", str(source),
        "--uarch", "--freq", str(frequency), "--verify",
        "--write-routed", str(routed), "-o", str(bitstream),
    ]
    env = dict(os.environ)
    env["PYTHONPATH"] = str(ROOT) + os.pathsep + env.get("PYTHONPATH", "")
    try:
        completed = subprocess.run(command, cwd=ROOT, env=env, text=True,
                                   stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                   timeout=timeout)
    except subprocess.TimeoutExpired as exc:
        output = exc.stdout or ""
        if isinstance(output, bytes):
            output = output.decode(errors="replace")
        completed = subprocess.CompletedProcess(command, 124, stdout=output +
                                                 "\nqualification timeout after %d seconds\n" % timeout)
    log = completed.stdout or ""
    values = re.search(r"MCU read-values.*?:\s*\[([^]]*)\]", log)
    observed = [] if not values else [int(item.strip(), 0)
                                      for item in values.group(1).split(",") if item.strip()]
    mapped = re.search(r"data pips: (\d+) total, (\d+) mapped.*?(\d+) unmapped", log)
    fmax = re.findall(r"Max frequency.*?:\s*([0-9.]+) MHz", log)
    result = {
        "schema": 1,
        "trial_id": tag,
        "seed": seed,
        "width": width,
        "mode": mode,
        "target_mhz": frequency,
        "returncode": completed.returncode,
        "reachable_values": observed,
        "post_route_mhz": float(fmax[-1]) if fmax else None,
        "source_sha256": _sha256_text(source),
    }
    if mapped:
        result.update(data_pips=int(mapped.group(1)), mapped_pips=int(mapped.group(2)),
                      unmapped_pips=int(mapped.group(3)))
    if bitstream.exists():
        result["bitstream_sha256"] = _sha256_binary(bitstream)
    if routed.exists():
        result["routed_sha256"] = _sha256_text(routed)
    result["passed"] = bool(
        completed.returncode == 0 and bitstream.exists() and routed.exists()
        and result.get("unmapped_pips") == 0 and len(set(observed)) > 2
    )
    if not result["passed"]:
        result["log_tail"] = log[-4000:]
    return result


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seeds", default="0:4", help="comma list and/or half-open ranges")
    parser.add_argument("--widths", default="8,16,32")
    parser.add_argument("--modes", default="lfsr,xorshift,mixed")
    parser.add_argument("--freq", type=float, default=25.0)
    parser.add_argument("--timeout", type=int, default=600)
    parser.add_argument("--out-dir", type=Path,
                        help="retain generated RTL, routed JSON, and bitstreams here")
    parser.add_argument("--evidence", type=Path,
                        help="append one JSON object per completed trial")
    args = parser.parse_args(argv)
    if args.freq <= 0:
        parser.error("--freq must be positive")
    seeds = _parse_range(args.seeds)
    widths = [int(value, 0) for value in args.widths.split(",") if value.strip()]
    modes = [value.strip() for value in args.modes.split(",") if value.strip()]
    for width in widths:
        if width < 4:
            parser.error("all widths must be at least 4")
    for mode in modes:
        if mode not in ("lfsr", "xorshift", "mixed"):
            parser.error("unknown mode %s" % mode)

    temporary = None
    if args.out_dir is None:
        temporary = tempfile.TemporaryDirectory(prefix="agamemnon_random_rtl_")
        directory = Path(temporary.name)
    else:
        directory = args.out_dir.resolve()
        directory.mkdir(parents=True, exist_ok=True)
    if args.evidence:
        args.evidence.parent.mkdir(parents=True, exist_ok=True)

    failures = 0
    for seed in seeds:
        for width in widths:
            for mode in modes:
                result = run_trial(seed, width, mode, args.freq, directory, args.timeout)
                print("%-22s %s  pips=%s  states=%s  fmax=%s"
                      % (result["trial_id"], "PASS" if result["passed"] else "FAIL",
                         result.get("data_pips", "?"), len(result["reachable_values"]),
                         result.get("post_route_mhz", "?")), flush=True)
                if args.evidence:
                    with args.evidence.open("a", encoding="utf-8") as handle:
                        handle.write(json.dumps(result, sort_keys=True) + "\n")
                failures += not result["passed"]
    if temporary:
        temporary.cleanup()
    print("random RTL campaign: %d trial(s), %d failure(s)" %
          (len(seeds) * len(widths) * len(modes), failures))
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
