# Fully-open bitgen for a SEQUENTIAL design routed by nextpnr-agrv.
# Input: a nextpnr 'generic' --write JSON. Output: a flashable AGRV2K .bin.
#   LUT INITs  -> physmap.init_bit_pos (byte-exact open LUT editor)
#   data pips  -> sel_byteexact.predict_pair (RMUX/IMUX/OMUX sel encoding)
#   clock      -> clk-0 spine (clk0_spine.json) + CFG_TILECLKMUX[0] on each clocked tile
#   integrity  -> CRC-32/BZIP2 over hdr+raw[:99932], big-endian (validated on silicon)
# A baseline supplies the tile-grid canvas only. The complete 164-byte global
# preamble is regenerated by preamble.py and never inherited from that image.
import json, struct, sys, re, csv, collections, os, hashlib
from pathlib import Path

def main(argv=None, environ=None):
    _ENGINE = os.path.dirname(os.path.abspath(__file__)); SRC = SRCA = os.path.join(os.path.dirname(_ENGINE), "chipdb")
    from agamemnon.engine.registry import CONSTANTS, options_from
    from agamemnon.engine import sel_byteexact as SB, physmap, lzw_codec as L
    from agamemnon.engine.bit_ownership import BitOwnershipTrace
    from agamemnon.engine.features.protocol import BitstreamContext
    from agamemnon.engine.features.carry import FEATURE as CARRY_FEATURE
    from agamemnon.engine.features.clocks import FEATURE as CLOCK_FEATURE
    from agamemnon.engine.features.physical_io import FEATURE as PHYSICAL_IO_FEATURE
    from agamemnon.engine.features.route_through import (
        FEATURE as ROUTE_THROUGH_FEATURE,
        RouteThroughPolicyError,
    )
    from agamemnon.engine.features.mcu_ahb import (
        FEATURE as MCU_AHB_FEATURE,
        exact_wire as _exact_mcu_wire,
    )
    from agamemnon.engine.features.mcu_gpio import FEATURE as MCU_GPIO_FEATURE
    from agamemnon.engine.features.routing import FEATURE as ROUTING_FEATURE
    OPTIONS = options_from(environ)
    argv = sys.argv if argv is None else argv
    if len(argv) < 3:
        sys.exit("usage: bitgen_seq.py <routed.json> <out.bin>")
    ROUTED, OUT = argv[1], argv[2]

    cell, bymux = SB.load_pips()
    routing_tables = ROUTING_FEATURE.load_selector_tables(Path(SRCA), OPTIONS)

    # BramTile (13,4) config cells (gen_bram_cell.py, from physical_map) -> merge into `cell` so the general
    # resolvers (mesh RMUX closed-form + IMUX crossbar closed-form) can emit (byte,mask) for BramTile muxes.
    # pips_full.csv is LogicTile-only; without these a BramTile-dst pip resolves a sel but finds no bit.
    import csv as _csv
    _bcell = os.path.join(SRC, "bram_cell.csv")
    if os.path.exists(_bcell):
        _nbc = 0
        for r in _csv.DictReader(open(_bcell)):
            cell[(int(r["x"]), int(r["y"]), r["mux"], int(r["sel"]))] = (int(r["byte"]), int(r["mask"]))
            _nbc += 1
        print("loaded %d BramTile config cells (bram_cell.csv)" % _nbc)

    # LE-internal slice config (the C-input Qin/Cin mux + carry) -- these bits are NOT in pips_full.csv;
    # they come from chipdb/slice_cfg.csv (gen_slice_cfg.py, from the vendor physical map). Needed for the
    # Qin self-feedback model: CFG_LUTCMUX[2z]=1 selects pinC<-Qin (byte-exact, extracted from the vendor
    # accumulator bin). See COUNTER_FREEZE_HANDOFF.md ⚠️ CORRECTION.
    SLICE_CFG = CARRY_FEATURE.load_slice_config(Path(SRC))

    ARCHIVAL_LEGACY = routing_tables.archival_legacy

    # MCU-edge BBMUXS input-select encoding: a BBMUXS field is a 2-hot {lo, hi} pair (lo in bank 0..3,
    # hi in bank 4..7) that depends ONLY on the SOURCE RMUX index (validated INSTANCE-independent: the
    # same source RMUX lights the same pair on different BBMUXS instances). Extracted byte-exact from four
    # oracle designs: RMUX92->(2,6), RMUX19->(1,6), RMUX25->(0,4), RMUX02->(1,4). NOTE: hi is NOT fixed at
    # 6 (that held only for RMUX92/19) nor lo+4 -- it's a genuine per-source pair (RMUX02->(1,4) and
    # RMUX25->(0,4) both have hi=4). Cross-validated: RMUX02->BBMUXS04 gives {1,4} in BOTH loop4 (folded,
    # +idle top-flag 8) and lutmcu4 (LUT-driven, no flag) -> the top-flag 8 is idle-only, not needed.
    # BufMUX/InputMUX/SinkMUXPseudo are 0-config passthrough/pseudo nodes (no CFG cell).
    mcue = {}   # (x,y,"BBMUXSn"|"BBMUXEn"|"BBMUXWn",sel_index) -> (byte,mask)
    for r in csv.DictReader(open(SRCA + "/pips_mcuedge.csv")):
        if r["mux"].startswith(("BBMUXS", "BBMUXE", "BBMUXW")):
            mcue[(int(r["x"]), int(r["y"]), r["mux"], int(r["sel_index"]))] = (int(r["byte"]), int(r["mask"]))
        elif r["mux"].startswith("InputMUX"):
            mcue[(int(r["x"]), int(r["y"]), r["mux"], int(r["sel_index"]))] = (int(r["byte"]), int(r["mask"]))

    # Exact node-local route fields from the protocol-valid, simultaneous 32-bit
    # HADDR-to-HRDATA vendor oracle.  Several of these physical edges have other
    # observations in the broad corpus with a different apparent pair because a
    # sibling node in the same CFG group was active.  A majority pair is therefore
    # not sufficient here: clear the one destination-node field and reproduce the
    # exact oracle codeword.  The table also includes the one-bit InputMUX fields
    # on BufMUX->InputMUX hard-boundary edges, which pips_full/sel_dataset do not
    # represent at all.
    EXACT_MCU_ADDR_PIP = MCU_AHB_FEATURE.load_exact_pip_fields(Path(SRCA))
    for _map_name in ("bram_x9_haddr_pip_cfg.csv",
                      "bram_x9_data5_pip_cfg.csv",
                      "bram_address_gnd_terminal_pip_cfg.csv",
                      "mcu_resetn_fabric_pip_cfg.csv", "mcu_local_int0_pip_cfg.csv",
                      "mcu_local_int1_pip_cfg.csv", "mcu_local_int2_pip_cfg.csv",
                      "mcu_local_int3_pip_cfg.csv",
                      "mcu_slave_ahb_response_pip_cfg.csv",
                      "mcu_slave_ahb_hrdata1_4_pip_cfg.csv",
                      "mcu_slave_ahb_hrdata5_8_pip_cfg.csv",
                      "mcu_slave_ahb_hrdata9_12_pip_cfg.csv",
                      "mcu_slave_ahb_hrdata13_16_pip_cfg.csv",
                      "mcu_slave_ahb_hrdata17_20_pip_cfg.csv",
                      "mcu_slave_ahb_hrdata21_24_pip_cfg.csv",
                      "mcu_slave_ahb_hrdata25_28_pip_cfg.csv",
                      "mcu_slave_ahb_hrdata29_31_pip_cfg.csv",
                      "mcu_slave_ahb_hrdata_grouped_full_pip_cfg.csv",
                      "mcu_slave_ahb_request_control_pip_cfg.csv",
                      "mcu_slave_ahb_request_payload_pip_cfg.csv",
                      "mcu_dma_response_all_pip_cfg.csv",
                      "mcu_dma_request_all_pip_cfg.csv",
                      "mcu_stop_pip_cfg.csv",
                      "analog_adc0_db0_pip_cfg.csv",
                      "analog_adc0_eoc_pip_cfg.csv",
                      "analog_adc0_db1_pip_cfg.csv"):
        _mapf = os.path.join(SRCA, _map_name)
        if not os.path.exists(_mapf):
            continue
        for _row_index, _r in enumerate(csv.DictReader(open(_mapf))):
            # Rows 0:20 are the silicon-qualified HADDR[2:5] x9 ingress.
            # The remaining rows are retained vendor-control facts used only
            # by the bounded full-address discriminator; its static result did
            # not qualify these selectors for global strict emission.
            if (_map_name == "bram_x9_haddr_pip_cfg.csv" and
                    _row_index >= 21 and
                    not OPTIONS.enabled("AGAMEMNON_X9_FULL_ADDRESS")):
                continue
            _src = _exact_mcu_wire(_r["src_wire"])
            _dst = _exact_mcu_wire(_r["dst_wire"])
            _key = _src + _dst
            _clear = tuple(int(v) for v in _r["clear_selectors"].split(";") if v != "")
            _set = tuple(int(v) for v in _r["set_selectors"].split(";") if v != "")
            _value = (_r["cell_table"], _r["cfg_group"], _clear, _set)
            if _key in EXACT_MCU_ADDR_PIP and EXACT_MCU_ADDR_PIP[_key] != _value:
                raise SystemExit("conflicting exact MCU corridor codeword for %s" % (_key,))
            EXACT_MCU_ADDR_PIP[_key] = _value
    for _key, _value in MCU_GPIO_FEATURE.load_exact_pip_fields(Path(SRCA)).items():
        if _key in EXACT_MCU_ADDR_PIP and EXACT_MCU_ADDR_PIP[_key] != _value:
            raise SystemExit("conflicting exact MCU GPIO corridor codeword for %s" % (_key,))
        EXACT_MCU_ADDR_PIP[_key] = _value
    if EXACT_MCU_ADDR_PIP:
        print("loaded %d exact protocol-valid AHB32 corridor fields" % len(EXACT_MCU_ADDR_PIP))
    # Exact, physical AHB hrdata edge encodings.  The vendor-routed 32-bit oracle
    # proved that selector pairs are not globally source-index invariant: RMUX43,
    # for example, uses a different pair at the y=11 east crossing than at y=12.
    # Key the pair by the complete source->edge identity and use the older source
    # tables only for the independently qualified alternate fan-ins above.
    MCU_EXIT_PAIR = {}
    _hl_names = ["mcu_hrdata_lanes.csv", "mcu_hrdata_addr_lanes.csv",
                 "mcu_ahb_response_controls.csv", "mcu_ahb_control_exit_pairs.csv",
                 "mcu_haddr_missing_exit_pairs.csv", "mcu_haddr_full_exit_pairs.csv"]
    _hl_names.append("bram_x9_data3_mcu_exit.csv")
    _hl_names.append("bram_x9_data4_mcu_exit.csv")
    _hl_names.append("bram_x9_data5_mcu_exit.csv")
    for _hl_name in _hl_names:
        _hl = os.path.join(SRCA, _hl_name)
        if not os.path.exists(_hl):
            continue
        for _r in csv.DictReader(open(_hl)):
            _em = re.fullmatch(r"(BBMUX[A-Z]+)0*([0-9]+)", _r["edge_res"])
            _sm = re.fullmatch(r"([A-Za-z]+)0*([0-9]+)", _r["src_res"])
            if not _em or not _sm:
                raise SystemExit("bad mcu_hrdata_lanes.csv resource: %s -> %s"
                                 % (_r["src_res"], _r["edge_res"]))
            _key = (int(_r["edge_x"]), int(_r["edge_y"]), _em.group(1), int(_em.group(2)),
                    int(_r["src_x"]), int(_r["src_y"]), _sm.group(1), int(_sm.group(2)))
            MCU_EXIT_PAIR[_key] = tuple(int(v) for v in _r["selectors"].split(";") if v)
    print("loaded %d exact AHB hrdata edge selector codewords" % len(MCU_EXIT_PAIR))
    d = json.load(open(ROUTED)); mod = d["modules"]["top"]
    carry_state = CARRY_FEATURE.prepare(mod, SLICE_CFG)

    # 1. LUT INITs (SRAM stores complement)
    # REGISTER-OUTPUT-SELECT = CFG_OMUX<z> sel=2 : presents the FF-Q (instead of the default LUT-F) on the
    # slice's mesh output OMUX[3z+2]. Proven byte-exact vs vendor oracles (AG32-Docs findings_regsel.md):
    # the isolated registered LE (regd) sets CFG_OMUX0[2]; the 8-bit counter sets CFG_OMUX<z>[2] for
    # EXACTLY the FFs whose Q routes via OMUX[3z+2]. Our arch models FF Q only on OMUX[3z+2], so every
    # used registered slice sets its CFG_OMUX<z> sel=2 bit. (The previous CFG_LUTCMUX[2z+1] was WRONG: it
    # is the carry/cascade-chain bit -- 0 in the isolated registered regd, but 1 for the counter's z=0
    # COMB glue LUT -- not the register-select. The oracle triple regd/combd/cnt disambiguates them.)
    # CFG_OMUX pips are already in `cell` (load_pips -> pips_full.csv), keyed (x,y,"CFG_OMUX<z>",sel).
    lut_sets = []
    reg_sets = []
    slices = []
    clocked_tiles = set()   # tiles containing a registered FF -> need the clock distributed to them
    _vout_all = OPTIONS.enabled("AGAMEMNON_VENDOR_OUT_ALL")
    _vout = OPTIONS.raw("AGAMEMNON_VENDOR_OUT_SLICE")
    _vout = OPTIONS.coordinates("AGAMEMNON_VENDOR_OUT_SLICE") if _vout else None
    _left_vout = (set(CONSTANTS["left_vendor_slices"].value)
                  if OPTIONS.enabled("AGAMEMNON_LEFT_PAD_OUT") else set())
    # Sites 4:7 were historically put in vendor-presentation mode whenever
    # direct-D was enabled; retained SERV evidence depends on that exact pack
    # policy. No additional site is admitted merely because it has a qualified
    # registered input consumer; that is not direct-D feedback evidence.
    _legacy_direct_d_sites = ({(14, 11, 4), (14, 11, 5),
                               (14, 11, 6), (14, 11, 7)}
                              if OPTIONS.enabled("AGAMEMNON_DIRECT_D") else set())
    for cn, c in mod["cells"].items():
        _cell_type = c.get("type")
        if _cell_type not in ("GENERIC_SLICE", "AGRV2K_DUAL_LUT_CONST"): continue
        bel = c["attributes"]["NEXTPNR_BEL"]
        mm = re.match(r"X(\d+)Y(\d+)_(?:DUAL_)?SLICE(\d+)", bel)
        x, y, z = int(mm.group(1)), int(mm.group(2)), int(mm.group(3))
        _direct_d_site = (x, y, z) in _legacy_direct_d_sites
        if _cell_type == "AGRV2K_DUAL_LUT_CONST":
            _value = int(c.get("parameters", {}).get("VALUE", "0"), 2)
            init = 0xFFFF if _value else 0
            bm = cell.get((x, y, "CFG_OMUX%d" % z, 0))
            if bm: reg_sets.append(bm)
        else:
            init = int(c["parameters"]["INIT"], 2)
        slices.append((x, y, z))
        _bram_sel = c.get("attributes", {}).get("AGRV2K_OMUX_SEL")
        _bram_sel = int(str(_bram_sel), 2) if _bram_sel is not None else None
        if int(c["parameters"].get("FF_USED", "0"), 2):        # registered slice -> present Q on OMUX[3z+2]
            # VENDOR-OUT slice (AGAMEMNON_VENDOR_OUT_SLICE="x,y,z"): the vendor-faithful output FF routes
            # F (LUT out) on OMUX[3z+0] and Q (feedback) on OMUX[3z+1] instead of the default OMUX[3z+2],
            # so it enters the silicon-conducting pad chain (OMUX42->RMUX74->RMUX09->pad) and feeds back
            # via the intra-tile crossbar (OMUX43->IMUX). CFG_OMUX<z> sel=b enables OMUX[3z+b] (proven by
            # the vendor pintest2 bits: slice14@(14,12) sets CFG_OMUX14 {0,1}). Emit sels {0,1} for it.
            _sels = ((0, 1) if (_vout_all or _vout == (x, y, z) or
                                (x, y, z) in _left_vout or
                                _direct_d_site)
                     else ((_bram_sel,) if _bram_sel is not None else (2,)))
            for _s in _sels:
                bm = cell.get((x, y, "CFG_OMUX%d" % z, _s))
                if bm: reg_sets.append(bm)
            clocked_tiles.add((x, y))
        elif _vout_all or (x, y, z) in _left_vout or _direct_d_site:
            # In vendor-output mode a combinational LUT is presented on
            # OMUX[3z+0]. This is used by exact carry-seam qualification where the
            # registered Q feedback wire must remain independent of the mesh tap.
            bm = cell.get((x, y, "CFG_OMUX%d" % z, 0))
            if bm: reg_sets.append(bm)
        elif _bram_sel is not None:
            # The vendor's conflict-free Port-B placement also uses alternate
            # combinational LUT presentation (not just alternate registered Q).
            # There is no cell-to-OMUX routing pip, so emit CFG_OMUX explicitly.
            bm = cell.get((x, y, "CFG_OMUX%d" % z, _bram_sel))
            if bm: reg_sets.append(bm)
        for b in range(16):
            byte, mask = physmap.init_bit_pos(x, y, z, b)
            if not ((init >> b) & 1): lut_sets.append((byte, mask))   # complement
    print("slices placed:", slices, "; LUT-init bits:", len(lut_sets))

    from agamemnon.engine.features.bram import FEATURE as BRAM_FEATURE
    bram_state = BRAM_FEATURE.prepare(mod, Path(SRC), OPTIONS)
    brams = bram_state.cells

    physical_io_state = PHYSICAL_IO_FEATURE.prepare(
        mod, Path(SRC), cell, ARCHIVAL_LEGACY
    )
    pips = physical_io_state.pips

    mcu_gpio_state = MCU_GPIO_FEATURE.prepare(mod, mcue)
    routing_state = ROUTING_FEATURE.prepare(
        pips=pips,
        cell=cell,
        options=OPTIONS,
        tables=routing_tables,
        physical_io_state=physical_io_state,
        exact_mcu_pips=EXACT_MCU_ADDR_PIP,
        mcu_cells=mcue,
        mcu_exit_pairs=MCU_EXIT_PAIR,
        bram_feature=BRAM_FEATURE,
        bram_state=bram_state,
        slice_config=SLICE_CFG,
        left_vendor_slices=_left_vout,
    )

    clock_state = CLOCK_FEATURE.prepare(
        clocked_tiles, reg_sets, brams, cell, Path(SRCA), OPTIONS
    )

    # 4. Assemble on the design-neutral tile-grid canvas. AGAMEMNON_BASELINE may
    # select an alternate canvas for research, but its preamble is replaced in
    # full below.
    _bl = OPTIONS.raw("AGAMEMNON_BASELINE", SRC + "/fabric_default.bin")
    base = open(_bl, "rb").read()
    hdr = base[:8]
    raw = bytearray(base[8:] if len(base) - 8 == CONSTANTS["raw_image_bytes"].value else L.decode(base[8:]))   # uncompressed .bin or LZW
    _trace_path = OPTIONS.raw("AGAMEMNON_OWNERSHIP_TRACE")
    _ownership = BitOwnershipTrace(len(raw)) if _trace_path else None
    def _owned(by, ms, owner):
        if _ownership is not None:
            _ownership.touch(by, ms, owner)
    oracle = set(k for k, (by, ms) in cell.items() if by < len(raw) and raw[by] & ms)
    abg = collections.defaultdict(set)
    for (x, y, mx, se) in oracle: abg[(x, y, mx)].add(se)
    sat = set(k for k, s in abg.items() if set(bymux.get(k, {})) and s == set(bymux.get(k, {})))
    for (x, y, mx, se), (by, ms) in cell.items():
        if mx.rstrip("0123456789") in ("CFG_RMUX", "CFG_IMUX") and (x, y, mx) not in sat and by < len(raw):
            raw[by] &= (~ms) & 0xFF
            _owned(by, ms, "default")
    # CLEAR each PLACED slice's LUT (16 bits) + OMUX (sel 0/1/2) so the baseline's residual slice config
    # can't corrupt the overlaid design. bitgen only OR's the design on; without this, a baseline LUT bit
    # the design leaves 0 stays set -> wrong LUT function. This was the real "stuck on a foreign baseline"
    # bug (mis-diagnosed as a clock failure): mcu_loop's LUT residue at the target tile corrupted the FF.
    for (x, y, z) in slices:
        for b in range(16):
            by, ms = physmap.init_bit_pos(x, y, z, b)
            if by < len(raw):
                raw[by] &= (~ms) & 0xFF
                _owned(by, ms, "LUT")
        for s in range(3):
            bm = cell.get((x, y, "CFG_OMUX%d" % z, s))
            if bm and bm[0] < len(raw):
                raw[bm[0]] &= (~bm[1]) & 0xFF
                _owned(bm[0], bm[1], "LUT")
    _carry_context = BitstreamContext(
        image=raw,
        module=mod,
        chipdb_root=Path(SRCA),
        options=OPTIONS,
        ownership=_ownership,
        state=carry_state,
    )
    CARRY_FEATURE.clear_bitstream(_carry_context)
    _physical_io_context = BitstreamContext(
        image=raw,
        module=mod,
        chipdb_root=Path(SRCA),
        options=OPTIONS,
        ownership=_ownership,
        state=physical_io_state,
    )
    PHYSICAL_IO_FEATURE.clear_bitstream(_physical_io_context)
    _routing_context = BitstreamContext(
        image=raw,
        module=mod,
        chipdb_root=Path(SRCA),
        options=OPTIONS,
        ownership=_ownership,
        state=routing_state,
    )
    ROUTING_FEATURE.clear_bitstream(_routing_context)
    _bram_context = BitstreamContext(
        image=raw,
        module=mod,
        chipdb_root=Path(SRCA),
        options=OPTIONS,
        ownership=_ownership,
        state=bram_state,
    )
    BRAM_FEATURE.clear_bitstream(_bram_context)
    ROUTING_FEATURE.emit_bitstream(_routing_context)
    _mcu_gpio_context = BitstreamContext(
        image=raw,
        module=mod,
        chipdb_root=Path(SRCA),
        options=OPTIONS,
        ownership=_ownership,
        state=mcu_gpio_state,
    )
    MCU_GPIO_FEATURE.emit_bitstream(_mcu_gpio_context)
    for by, ms in lut_sets:
        if by < len(raw):
            raw[by] |= ms
            _owned(by, ms, "LUT")
    _clock_context = BitstreamContext(
        image=raw,
        module=mod,
        chipdb_root=Path(SRCA),
        options=OPTIONS,
        ownership=_ownership,
        state=clock_state,
    )
    CLOCK_FEATURE.emit_bitstream(_clock_context)
    PHYSICAL_IO_FEATURE.emit_bitstream(_physical_io_context)
    for by, ms in reg_sets:
        if by < len(raw):
            raw[by] |= ms
            _owned(by, ms, "register_mode")
    BRAM_FEATURE.emit_bitstream(_bram_context)
    CARRY_FEATURE.emit_bitstream(_carry_context)
    try:
        _route_through_write_count = ROUTE_THROUGH_FEATURE.emit_bitstream(
            BitstreamContext(
                image=raw,
                module=mod,
                chipdb_root=Path(SRCA),
                options=OPTIONS,
                ownership=_ownership,
            )
        )
    except RouteThroughPolicyError as exc:
        raise SystemExit(str(exc))
    if _route_through_write_count:
        print("complete route-through footprint bytes: %d" % _route_through_write_count)

    CLOCK_FEATURE.emit_global(_clock_context)
    print("registered slices (CFG_OMUX<z> sel=2 set): %d" % len(reg_sets))
    def crc32_bzip2(dd):
        c = 0xFFFFFFFF
        for b in dd:
            c ^= b << 24
            for _ in range(8): c = ((c << 1) ^ CONSTANTS["crc_polynomial"].value) & 0xFFFFFFFF if (c & 0x80000000) else (c << 1) & 0xFFFFFFFF
        return c ^ 0xFFFFFFFF
    PHYSICAL_IO_FEATURE.emit_pad_inputs(_physical_io_context)
    _crc_end = CONSTANTS["crc_payload_bytes"].value
    raw[_crc_end:_crc_end + 4] = struct.pack(">I", crc32_bzip2(bytes(hdr) + bytes(raw[:_crc_end])))
    if _ownership is not None:
        _ownership.touch_bytes(_crc_end, _crc_end + 4, "integrity")
    out = hdr + L.encode(bytes(raw))
    open(OUT, "wb").write(out)
    if _ownership is not None:
        _ownership.write_json(
            _trace_path,
            bytes(raw),
            source=os.path.normpath(ROUTED).replace("\\", "/"),
            # The CLI's canonical artifact is the 8-byte header plus decoded
            # payload.  ``out`` here is only the compressed handoff to the
            # wrapper, so anchoring it made an otherwise correct byte-exact
            # replay look unrelated to its retained 99,944-byte image.
            output_sha256=hashlib.sha256(hdr + bytes(raw)).hexdigest(),
        )
        print("wrote ownership trace %s" % _trace_path)
    print("wrote %s (%d B); re-decodes to %d B raw" % (OUT, len(out), len(L.decode(out[8:]))))

if __name__ == "__main__":
    main()
