function(ag32_firmware TARGET)
  set(options)
  set(oneValueArgs LINKER OUTPUT)
  set(multiValueArgs SOURCES INCLUDES)
  cmake_parse_arguments(AG32 "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(NOT AG32_LINKER)
    message(FATAL_ERROR "ag32_firmware requires LINKER")
  endif()
  add_executable(${TARGET} ${AG32_SOURCES})
  target_include_directories(${TARGET} PRIVATE ${AG32_INCLUDES})
  target_link_options(${TARGET} PRIVATE -nostdlib -T${AG32_LINKER} -Wl,--gc-sections)
  set(output "${AG32_OUTPUT}")
  if(NOT output)
    set(output "${CMAKE_CURRENT_BINARY_DIR}/${TARGET}.bin")
  endif()
  add_custom_command(TARGET ${TARGET} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O binary $<TARGET_FILE:${TARGET}> ${output}
    BYPRODUCTS ${output})
endfunction()
