[project]
name = "@PROJECT_NAME@"
board = "ag32vf303-l48"
device = "AGRV2KL48"

[fabric]
output = "build/fabric.bin"
qualified_profile = "l48-complete-byte-waited-2026-08-05"

[mcu]
sources = ["src/main.c"]
linker = "@sdk/link_sram.ld"
output = "build/mcu.bin"
