#!/usr/bin/env python3
"""Generate/check the AG32 family coverage matrix (T25, GOAL_AG32_FAMILY_COVERAGE.md).

Source of truth is ``agamemnon/sdk/family_coverage_matrix.json`` (hand-authored,
cross-checked against ``agamemnon/engine/family.py`` and ``device.py`` by this
script's ``--check``). This script only renders that JSON into a human-readable
Markdown doc; it never invents a tier.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from agamemnon.engine import device as _device       # noqa: E402
from agamemnon.engine import family as _family        # noqa: E402


MATRIX_PATH = ROOT / "agamemnon" / "sdk" / "family_coverage_matrix.json"
DOC_PATH = ROOT / "docs" / "FAMILY_COVERAGE_MATRIX.md"

VALID_TIERS = {"silicon-qualified", "build-supported", "recovered-only", "n/a"}
SURFACE_LABELS = {
    "config_accept": "config-accept",
    "pad_out": "pad-out",
    "pad_in": "pad-in",
    "oe": "OE",
    "flash_prog_backup": "flash prog/backup",
    "psram": "PSRAM",
    "peripherals": "peripherals",
}
TIER_MARK = {
    "silicon-qualified": "silicon-qualified",
    "build-supported": "build-supported",
    "recovered-only": "recovered-only",
    "n/a": "n/a",
}


def load_matrix():
    return json.loads(MATRIX_PATH.read_text(encoding="utf-8"))


def validate_matrix(data):
    """Fail-closed structural + cross-registry checks. Raises ValueError."""
    if data.get("schema") != 1:
        raise ValueError("family_coverage_matrix.json: unsupported schema")
    surfaces = data["surfaces"]
    if list(surfaces) != sorted(SURFACE_LABELS, key=list(SURFACE_LABELS).index):
        # Order is significant for the rendered table but not for correctness;
        # just require the same *set*.
        if set(surfaces) != set(SURFACE_LABELS):
            raise ValueError("family_coverage_matrix.json: surfaces must match SURFACE_LABELS exactly")
    if set(data["parts"]) != set(_family.PART_NAMES):
        raise ValueError("family_coverage_matrix.json: parts must match agamemnon.engine.family.PART_NAMES exactly")

    for part_name, part_data in data["parts"].items():
        part = _family.get_part(part_name)
        cells = part_data["cells"]
        if set(cells) != set(surfaces):
            raise ValueError("%s: cells must cover every surface exactly" % part_name)
        for surface, cell in cells.items():
            tier = cell.get("tier")
            if tier not in VALID_TIERS:
                raise ValueError("%s/%s: invalid tier %r" % (part_name, surface, tier))
            if not cell.get("note"):
                raise ValueError("%s/%s: missing note" % (part_name, surface))
            if "evidence" not in cell or not isinstance(cell["evidence"], list):
                raise ValueError("%s/%s: missing evidence list" % (part_name, surface))
            # PSRAM must be n/a exactly for the non-VH parts, and never n/a for
            # the VH parts (they carry a real 8MB HyperRAM interface).
            if surface == "psram":
                has_psram = part.psram_bytes > 0
                if has_psram and tier == "n/a":
                    raise ValueError("%s: has PSRAM but psram cell is n/a" % part_name)
                if not has_psram and tier != "n/a":
                    raise ValueError("%s: has no PSRAM but psram cell is %r" % (part_name, tier))
            # Never-wrong rule: silicon-qualified requires a recorded qualified
            # board for that exact part. This is the hard backstop against
            # ever silently promoting a part with no evidence record.
            if tier == "silicon-qualified" and not part.has_qualified_board:
                raise ValueError(
                    "%s/%s: marked silicon-qualified but family.py has_qualified_board=False"
                    % (part_name, surface)
                )


def render_doc(data):
    surfaces = data["surfaces"]
    lines = [
        "# AG32 family coverage matrix",
        "",
        "Generated by `tools/generate_family_coverage_matrix.py` from "
        "`agamemnon/sdk/family_coverage_matrix.json`; do not edit by hand.",
        "",
        "Rows are the seven AG32 family part numbers "
        "(`tools/AG32_RefManual.txt` Sec 1.2, transcribed in "
        "`agamemnon/engine/family.py`); columns are the surfaces "
        "`GOAL_AG32_FAMILY_COVERAGE.md` tracks. **Building for a part is never "
        "a silicon claim for that part** -- a fabric-logic-only build "
        "(`build-supported`) works family-wide because the AGRV2K fabric is "
        "identical across the family; a `silicon-qualified` cell requires a "
        "recorded, reviewed evidence trail on that exact physical part.",
        "",
        "## Tiers",
        "",
        "| Tier | Meaning |",
        "|---|---|",
    ]
    for tier, meaning in data["tiers"].items():
        lines.append("| `%s` | %s |" % (tier, meaning))
    lines.extend(["", "## Matrix", "", "| Part | Package | " + " | ".join(
        SURFACE_LABELS[s] for s in surfaces
    ) + " |", "|---|---|" + "---|" * len(surfaces)])
    for part_name in _family.PART_NAMES:
        part = _family.get_part(part_name)
        cells = data["parts"][part_name]["cells"]
        row = ["`%s`" % part_name, part.package_name]
        for surface in surfaces:
            row.append(TIER_MARK[cells[surface]["tier"]])
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")
    lines.append("## Notes per cell")
    lines.append("")
    for part_name in _family.PART_NAMES:
        part = _family.get_part(part_name)
        cells = data["parts"][part_name]["cells"]
        lines.append("### `%s` (%s)" % (part_name, part.package_name))
        lines.append("")
        lines.append("%s" % part.board_note)
        lines.append("")
        lines.append("| Surface | Tier | Note |")
        lines.append("|---|---|---|")
        for surface in surfaces:
            cell = cells[surface]
            lines.append("| %s | `%s` | %s |" % (SURFACE_LABELS[surface], cell["tier"], cell["note"]))
        lines.append("")
    lines.append("## Standing notes")
    lines.append("")
    # Each JSON entry is a wrapped line of one flowing paragraph, not an
    # independent bullet -- join them back into prose.
    lines.append(" ".join(data["notes"]))
    lines.append("")
    return "\n".join(lines)


def generated_outputs():
    data = load_matrix()
    validate_matrix(data)
    return {DOC_PATH: render_doc(data)}


def main(argv=None):
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        outputs = generated_outputs()
    except ValueError as exc:
        raise SystemExit("family coverage matrix validation failed: %s" % exc)
    stale = []
    for path, content in outputs.items():
        if args.write:
            with path.open("w", encoding="utf-8", newline="\n") as stream:
                stream.write(content)
            print("wrote %s" % path.relative_to(ROOT))
        elif not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(str(path.relative_to(ROOT)))
    if stale:
        raise SystemExit("stale generated family coverage output: %s" % ", ".join(stale))


if __name__ == "__main__":
    main()
