#!/usr/bin/env python3
"""Generate/check the D0 registry ledger and retained-artifact dry run."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from agamemnon.engine.claim_policy import ClaimPolicyError, evaluate_policy
from agamemnon.engine.registry import POLICY_VERSION, manifest, options_from


DRY_RUN_PATH = ROOT / "qualification" / "claim_policy_dry_run.json"
LEDGER_PATH = ROOT / "docs" / "CLAIM_POLICY_LEDGER.md"
PACK_MANIFEST_PATH = ROOT / "qualification" / "pack_regression.json"


def canonical_json_sha(data):
    encoded = json.dumps(data, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def canonical_lf_sha(path):
    """Hash text by the repository's cross-platform canonical-LF rule."""
    encoded = path.read_text(encoding="utf-8").encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def build_dry_run():
    pack = json.loads(PACK_MANIFEST_PATH.read_text(encoding="utf-8"))
    records = []
    for artifact in pack["artifacts"]:
        environment = dict(artifact["environment"])
        try:
            decision = evaluate_policy(options_from(environment))
            errors = []
            selected_counts = {}
            for row in decision.selected:
                selected_counts[row["kind"]] = selected_counts.get(row["kind"], 0) + 1
        except ClaimPolicyError as exc:
            decision = None
            errors = str(exc).splitlines()[1:]
            selected_counts = {}
        records.append({
            "routed": artifact["routed"],
            "routed_sha256": artifact["routed_sha256"],
            "expected_bitstream_sha256": artifact["bitstream_sha256"],
            "environment": environment,
            "policy": decision.policy if decision else environment.get("AGAMEMNON_STRICT_POLICY", "release-strict"),
            "selected_counts": selected_counts,
            "permission_errors": errors,
        })
    return {
        "schema": 1,
        "kind": "agamemnon-claim-policy-dry-run",
        "policy_version": POLICY_VERSION,
        "source": "qualification/pack_regression.json",
        "source_sha256": canonical_lf_sha(PACK_MANIFEST_PATH),
        "registry_manifest_sha256": canonical_json_sha(manifest()),
        "summary": {
            "artifact_count": len(records),
            "permission_error_count": sum(len(row["permission_errors"]) for row in records),
        },
        "artifacts": records,
    }


def render_ledger():
    data = manifest()
    lines = [
        "# D0 Claim Policy Ledger",
        "",
        "Generated by `tools/generate_claim_policy_ledger.py`; do not edit by hand.",
        "Maturity and evidence tier are independent axes. `preexisting_v4` entries",
        "backfill the already-approved release scope and are not new promotions.",
        "",
        "Policy version: `%s`." % data["policy_version"],
        "",
    ]
    for heading, key in (("Emitted features", "features"), ("Engine options", "options"), ("Silicon-derived constants", "constants")):
        lines.extend([
            "## %s" % heading,
            "",
            "| ID | Maturity | Evidence tier | Domain | Approval | Scope | Evidence |",
            "|---|---|---|---|---|---|---|",
        ])
        for row in data[key]:
            evidence_refs_html = "<br>".join(row["evidence_refs"])
            lines.append(
                "| `{name}` | {maturity} | {evidence_tier} | {claim_domain} | {approval_state} | {claim_scope} | {evidence_refs_html} |".format(
                    evidence_refs_html=evidence_refs_html, **row
                )
            )
        lines.append("")
    lines.extend([
        "## Enforcement rules",
        "",
        "- `release-strict` admits only release maturity with reviewed statistical or individual evidence.",
        "- D0 default-promotion amendment: when its hash-approval artifact "
        "(`chipdb/d0_default_promotion_approval.json`) is present and binds the "
        "exact reviewed routing-selector admission bytes, `differentially_validated` "
        "witnessed-routing rows in an approved population wave-dossier become "
        "eligible in the default release graph for their exact witnessed L48 "
        "routing-selection scope, with no opt-in flag; without that approval they "
        "stay experimental-opt-in and denied by default. Predicted/decoded/"
        "unwitnessed material never becomes default-eligible under any gate state.",
        "- `experimental-strict` requires each emitting experimental ID to be explicit and differentially validated or higher.",
        "- `research-unsafe` requires the separate explicit gate, may consume decoded/conflicted/predicted data, and never promotes it to release or experimental-strict evidence.",
        "- Statistical admission requires at least 300 zero-failure trials, 10 images, 3 contexts, 3 SRAM load/reset cycles, and a 95% rule-of-three upper bound no greater than 1%.",
        "- Electrical, timing, destructive, and safety-sensitive individual-only domains cannot be promoted statistically.",
        "- Under both strict policies, missing/inconsistent metadata, conflicts, unknowns, negative contradiction, and archival/unmapped emission fail closed.",
        "- Experimental-strict and research-unsafe builds emit a hash-bound non-release policy sidecar; negative-evidence routing edges remain blocked under every policy (the historical set is currently empty).",
        "",
    ])
    return "\n".join(lines)


def generated_outputs():
    dry = json.dumps(build_dry_run(), indent=2, sort_keys=True) + "\n"
    return {DRY_RUN_PATH: dry, LEDGER_PATH: render_ledger()}


def main(argv=None):
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    stale = []
    for path, content in generated_outputs().items():
        if args.write:
            with path.open("w", encoding="utf-8", newline="\n") as stream:
                stream.write(content)
            print("wrote %s" % path.relative_to(ROOT))
        elif not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(str(path.relative_to(ROOT)))
    if stale:
        raise SystemExit("stale generated claim-policy output: %s" % ", ".join(stale))


if __name__ == "__main__":
    main()
